"use strict";
module.exports = (sequelize, Sequelize) => {
  const KnowledgeSummary = sequelize.define(
    "KnowledgeSummary",
    {
      id: { autoIncrement: true, primaryKey: true, type: Sequelize.BIGINT },
      companyId: { type: Sequelize.BIGINT, allowNull: false },
      content: { type: Sequelize.TEXT, allowNull: true }, // rich text HTML
      isAutoGenerated: { type: Sequelize.BOOLEAN, allowNull: false, defaultValue: true },
      isDeleted: { type: Sequelize.BOOLEAN, allowNull: false, defaultValue: false },
      createdAt: { type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.NOW },
      updatedAt: { type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.NOW },
    },
    { timestamps: true }
  );

  KnowledgeSummary.associate = function (models) {
    KnowledgeSummary.belongsTo(models.Company, {
      foreignKey: "companyId",
      onDelete: "CASCADE",
      onUpdate: "CASCADE",
      constraints: true,
    });
  };

  return KnowledgeSummary;
};